### ISSUE TITLE
Scarlet Keys Set and Dossiers has images overlapping instruction text

### ISSUE THREAD

**Issue by tobabski** [Antimarkovnikov/AHC_CYOA#27]
On pages 15, 22, 35, 43 and 48 the instructions when the case file is present are obscured.

On pages 12 and 18, there are no instructions if the case file is present. Not sure if that was intentional or not for those items.

**Comment by Antimarkovnikov** [comment]
That is intentional on all of those instances.  The file numbers corelate to the page number in the official campaign guide.   So, the pages that you listed here corelate to setup instructions and resolutions in the official campaign guide and are just fun easter eggs I put into my campaign guide to keep the same page number effect.
