### ISSUE TITLE
Thank you and a question

### ISSUE THREAD

**Issue by Bpgoa** [Antimarkovnikov/AHC_CYOA#5]
Hi.. First of all Thank You for doing this.. I can see the work that has gone into the project and will definitely be printing them.

So the Question... I'm pretty new to AH, and was wondering if you had included the "Return To" content into the books?  I haven't purchased any of those sets yet, so don't know what comes with them / any new rules.  

Cheers 

A.

**Comment by Antimarkovnikov** [comment]
You're welcome! And an answer...

So, the Return to Expansions have different things that they add to the experience.  Most of what they add is additional or different encounter sets.  It also includes setup cards for the return to version of the scenario that tells you how to substitute in the new encounter sets.  All of the expansions thus far have these.  But the later ones, including The Forgotten Age and The Circle Undone have added additional introductions and resolutions.  It's these additional campaign text that I have included in my books.  But not setup instructions from the return to scenario cards.

For instance, there is no return to book for The Dunwich Legacy because there were no campaign guide changes to the campaign.

Hope that answers your questions. If not feel free to ask more here.
Thanks,
Antimarkovnikov

**Comment by Bpgoa** [comment]
Thank you for your reply..  Perfectly clear..
